version: "3.4"

services:
  traefik:
    image: traefik:1.7
    container_name: traefik
    domainname: ${DOMAINNAME:?}
    restart: always
    networks:
      - local
      - traefik_proxy
    ports:
      - "80:80"
      - "8081:8080"
      - "443:443"
    volumes:
      - ./traefikshared:/shared
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.${DOMAINNAME:?}"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME:?}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.auth.basic.usersFile=/shared/.htpasswd"
      - "com.centurylinklabs.watchtower.enable=false"
    command:
      - "--api"
      - "--api.entrypoint=traefik"
      - "--api.dashboard=true"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--acme"
      - "--acme.storage=/etc/traefik/acme/acme.json"
      - "--acme.entryPoint=https"
      - "--acme.httpChallenge.entryPoint=http"
      - "--acme.onHostRule=true"
      - "--acme.onDemand=false"
      - "--acme.email=${EMAIL_CONTACT:?}"
      - "--acme.acmeLogging=true"
      - "--acme.onDemand=false"
      - "--docker"
      - "--docker.endpoint=unix:///var/run/docker.sock"
      - "--docker.domain=${DOMAINNAME:?}"
      - "--docker.watch=true"
      - "--docker.exposedbydefault=false"

  # Use this command to find any issues: docker-compose logs -tf --tail="50" traefik

  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    # Automatically choose 'Manage the Docker instance where Portainer is running' by adding <--host=unix:///var/run/docker.sock> to the command
    # Automaticlly import the custom openeyes template on first run
    command:
      - "-H"
      - "unix:///var/run/docker.sock"
      - "--template-file"
      - "/templates/openeyes-templates.json"
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host:portainer.${DOMAINNAME:?}"
      - "traefik.port=9000"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME:?}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainerdata:/data
      - ./templates:/templates

networks:
  traefik_proxy:
  local:
    driver: bridge
